"""Conversations and their messages.

Stored rather than held in the browser for two reasons that have nothing to do
with convenience: an answer that cited a document is evidence of what the
assistant told an employee, and the audit trail is worth very little if the
thing being audited only exists in someone's tab.
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import ForeignKey, Index, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.ids import new_id
from app.db.base import Base, TimestampMixin
from app.db.types import UtcDateTime


class Conversation(Base, TimestampMixin):
    __tablename__ = "conversations"
    __table_args__ = (Index("ix_conversations_user_id_updated_at", "user_id", "updated_at"),)

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    user_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    # Taken from the first question rather than generated by a model. A title is
    # not worth an API call, and "What does error code E-04 mean?" is a better
    # label than anything a summariser would produce.
    title: Mapped[str] = mapped_column(String(200), nullable=False)

    messages: Mapped[list[ChatMessage]] = relationship(
        back_populates="conversation",
        cascade="all, delete-orphan",
        order_by="ChatMessage.created_at",
    )


class ChatMessage(Base):
    __tablename__ = "chat_messages"
    __table_args__ = (
        Index("ix_chat_messages_conversation_id_created_at", "conversation_id", "created_at"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    conversation_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("conversations.id", ondelete="CASCADE"), nullable=False
    )
    role: Mapped[str] = mapped_column(String(16), nullable=False)  # "user" | "assistant"
    content: Mapped[str] = mapped_column(Text, nullable=False)

    # Resolved server-side before the response leaves the API, then stored as
    # written. A citation is only meaningful alongside the exact wording it was
    # attached to, so the two are saved together and never recomputed.
    citations: Mapped[str | None] = mapped_column(Text, nullable=True)

    # What the answer cost, denormalised from usage_events so a conversation can
    # be shown with its cost without a join per message.
    input_tokens: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    output_tokens: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    latency_ms: Mapped[int | None] = mapped_column(Integer, nullable=True)

    created_at: Mapped[datetime] = mapped_column(UtcDateTime, nullable=False)

    conversation: Mapped[Conversation] = relationship(back_populates="messages")
